service: serverless-synaptic

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-central-1

functions:
  learn:
    handler: handler.learn
    events:
      - schedule: rate(1 day)
      - http:
          path: learn
          method: GET
  predict:
    handler: handler.predict
    events:
      - http:
          path: predict
          method: GET
