service: serverless-synaptic

custom:
  dataBucketName: serverless-synaptic-data
  modelBucketName: serverless-synaptic-model

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-central-1
  environment:
    DATA_BUCKET: ${self:custom.dataBucketName}
    MODEL_BUCKET: ${self:custom.modelBucketName}

functions:
  learn:
    handler: handler.learn
    events:
      - schedule: rate(1 day)
      - http:
          path: learn
          method: GET
  predict:
    handler: handler.predict
    events:
      - http:
          path: predict
          method: GET
resources:
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.modelBucketName}
        AccessControl: Private
        CorsConfiguration:
          CorsRules:
          - AllowedMethods:
            - GET
            - PUT
            - POST
            - HEAD
            AllowedOrigins:
            - "*"
            AllowedHeaders:
            - "*"
